spring.application.name=training-of-spring-boot-security

#setting the port to 6767
server.port = 6767

# set custom credential
spring.security.user.name=ahmed
spring.security.user.password=ahmedpass

# MySQl config
spring.datasource.url = jdbc:mysql://127.0.0.1:3306/userData
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.username= root
spring.datasource.password= 123ahmed